export const incidentsData = [
  {
    incidentId: "INC001",
    description: "Unauthorized Access Attempt on robert-laptop14",
    severity: "High",
    status: "Open",
    alertIds: ["1", "13"],
    timestamp: "2023-09-30T17:20:00Z",
    additionalInfo: "Multiple failed login attempts detected.",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC002",
    description: "Virus Detected on server03",
    severity: "Critical",
    status: "Open",
    alertIds: ["2"],
    timestamp: "2023-09-30T16:50:00Z",
    additionalInfo: "A virus signature (XYZ123) was identified.",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC003",
    description: "Network Port Scan Detected on server07",
    severity: "Medium",
    status: "Open",
    alertIds: ["6"],
    timestamp: "2023-09-30T14:55:00Z",
    additionalInfo: "Scanned ports: 22, 80, 443",
    assignedTo: "Network Team",
    resolution: "",
  },
  {
    incidentId: "INC004",
    description: "High CPU Usage on john-workstation01",
    severity: "High",
    status: "Open",
    alertIds: ["1"],
    timestamp: "2023-09-30T14:35:00Z",
    additionalInfo: "CPU usage exceeded 90% for 5 minutes.",
    assignedTo: "IT Support",
    resolution: "",
  },
  {
    incidentId: "INC005",
    description: "Failed Login Attempts on jacob-laptop19",
    severity: "Medium",
    status: "Open",
    alertIds: ["12"],
    timestamp: "2023-09-30T16:30:00Z",
    additionalInfo: "Multiple failed login attempts detected from IP 192.168.1.106.",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC006",
    description: "Disk Space Low on oliver-workstation20",
    severity: "Medium",
    status: "Open",
    alertIds: ["7"],
    timestamp: "2023-09-29T17:30:00Z",
    additionalInfo: "Free disk space is less than 5GB.",
    assignedTo: "IT Support",
    resolution: "",
  },
  {
    incidentId: "INC007",
    description: "Security Patch Missing on matthew-server21",
    severity: "High",
    status: "Open",
    alertIds: ["8"],
    timestamp: "2023-09-30T10:15:00Z",
    additionalInfo: "Critical security patch is missing (CVE-2023-12345).",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC008",
    description: "Unauthorized File Access on emma-laptop22",
    severity: "High",
    status: "Open",
    alertIds: ["3"],
    timestamp: "2023-09-30T17:45:00Z",
    additionalInfo: "Attempt to access sensitive files (financial_report.xlsx).",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC009",
    description: "Antimalware Update Failed on ava-desktop23",
    severity: "Medium",
    status: "Open",
    alertIds: ["4"],
    timestamp: "2023-09-30T13:25:00Z",
    additionalInfo: "Failed to download antimalware update.",
    assignedTo: "IT Support",
    resolution: "",
  },
  {
    incidentId: "INC010",
    description: "Intrusion Attempt Detected on noah-server24",
    severity: "High",
    status: "Open",
    alertIds: ["5"],
    timestamp: "2023-09-30T14:55:00Z",
    additionalInfo: "Intrusion attempt was blocked (IP 192.168.1.105).",
    assignedTo: "Security Team",
    resolution: "",
  },
  {
    incidentId: "INC011",
    description: "Disk Space Low on grace-workstation25",
    severity: "Low",
    status: "Open",
    alertIds: ["8"],
    timestamp: "2023-09-30T18:10:00Z",
    additionalInfo: "Free disk space is less than 15GB.",
    assignedTo: "IT Support",
    resolution: "",
  },
  {
    incidentId: "INC012",
    description: "Unauthorized Software Installation on olivia-laptop26",
    severity: "Medium",
    status: "Open",
    alertIds: ["9"],
    timestamp: "2023-09-30T16:20:00Z",
    additionalInfo: "Unauthorized software 'unapproved_application.exe' was installed.",
    assignedTo: "Security Team",
    resolution: "",
  },
];
