export const incidentData = [
  {
    incidentType: "Security Breach",
    dateTime: new Date(),
    sourceIp: "192.168.1.100",
    targetIp: "10.0.0.5",
    description: "Unauthorized access to a critical system.",
    status: "Open",
  },
  {
    incidentType: "Malware Outbreak",
    dateTime: new Date(),
    sourceIp: "10.0.0.10",
    targetIp: "192.168.1.200",
    description: "Widespread malware infection detected.",
    status: "Open",
  },
  {
    incidentType: "Data Exfiltration",
    dateTime: new Date(),
    sourceIp: "192.168.1.50",
    targetIp: "8.8.8.8",
    description: "Sensitive data sent to an external IP address.",
    status: "Open",
  },
  {
    incidentType: "Phishing Attack",
    dateTime: new Date(),
    sourceIp: "203.0.113.45",
    targetIp: "192.168.1.201",
    description: "Phishing email clicked by multiple users.",
    status: "Open",
  },
  {
    incidentType: "System Downtime",
    dateTime: new Date(),
    sourceIp: "0.0.0.0",
    targetIp: "10.0.0.20",
    description: "Server hardware failure causing downtime.",
    status: "Open",
  },
  {
    incidentType: "Unauthorized Access",
    dateTime: new Date(),
    sourceIp: "192.168.1.101",
    targetIp: "10.0.0.30",
    description: "User with insufficient privileges accessing critical data.",
    status: "Open",
  },
  {
    incidentType: "Data Loss",
    dateTime: new Date(),
    sourceIp: "10.0.0.40",
    targetIp: "192.168.1.60",
    description: "Critical data files deleted unexpectedly.",
    status: "Open",
  },
  {
    incidentType: "Brute-Force Attack",
    dateTime: new Date(),
    sourceIp: "10.0.0.50",
    targetIp: "192.168.1.70",
    description: "Multiple failed login attempts from the same IP address.",
    status: "Open",
  },
  {
    incidentType: "Network Intrusion",
    dateTime: new Date(),
    sourceIp: "192.168.1.80",
    targetIp: "10.0.0.60",
    description: "Unusual network traffic pattern detected.",
    status: "Open",
  },
  {
    incidentType: "Application Vulnerability",
    dateTime: new Date(),
    sourceIp: "10.0.0.70",
    targetIp: "192.168.1.90",
    description: "Exploitation of a known application vulnerability.",
    status: "Open",
  },
];
