export const threatIntlData = [
  {
    indicator: "192.168.1.100",
    indicatorType: "IP Address",
    description: "Known command and control server IP",
    source: "Threat Intelligence Feed A",
    confidenceLevel: "High",
    severity: "Critical",
    dateAdded: "2023-09-15T14:30:00Z",
    tags: ["Malware", "Botnet", "APT"],
    referenceLinks: [
      "https://www.example.com/threat-report-12345",
      "https://www.example.com/malware-analysis-67890",
    ],
  },

  {
    indicator: "example.com",
    indicatorType: "Domain",
    description: "Phishing domain associated with campaign XYZ",
    source: "Threat Intelligence Feed B",
    confidenceLevel: "Medium",
    severity: "High",
    dateAdded: "2023-09-17T09:45:00Z",
    tags: ["Phishing", "Campaign XYZ"],
    referenceLinks: [
      "https://www.example.com/phishing-report-54321",
      "https://www.example.com/campaign-xyz-analysis",
    ],
  },

  {
    indicator: "CVE-2023-12345",
    indicatorType: "Vulnerability",
    description: "Critical remote code execution vulnerability",
    source: "National Vulnerability Database (NVD)",
    confidenceLevel: "High",
    severity: "Critical",
    dateAdded: "2023-09-10T16:15:00Z",
    tags: ["CVE", "Remote Code Execution"],
    referenceLinks: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-12345",
      "https://www.example.com/vulnerability-patch-advisory",
    ],
  },

  {
    indicator: "APT Group 42",
    indicatorType: "Threat Actor",
    description:
      "Advanced Persistent Threat group known for targeting financial institutions",
    source: "Threat Intelligence Feed C",
    confidenceLevel: "High",
    severity: "High",
    dateAdded: "2023-09-20T11:00:00Z",
    tags: ["APT", "Financial Sector"],
    referenceLinks: [
      "https://www.example.com/apt-group-profile",
      "https://www.example.com/financial-sector-threat-report",
    ],
  },
  {
    indicator: "192.168.1.100",
    indicatorType: "IP Address",
    description: "Known command and control server IP",
    source: "Threat Intelligence Feed A",
    confidenceLevel: "High",
    severity: "Critical",
    dateAdded: "2023-09-15T14:30:00Z",
    tags: ["Malware", "Botnet", "APT"],
    referenceLinks: [
      "https://www.example-threat-intel-site.com/threat-report-12345",
      "https://www.example-malware-analysis-site.com/malware-analysis-67890",
    ],
  },
  {
    indicator: "example.com",
    indicatorType: "Domain",
    description: "Phishing domain associated with campaign XYZ",
    source: "Threat Intelligence Feed B",
    confidenceLevel: "Medium",
    severity: "High",
    dateAdded: "2023-09-17T09:45:00Z",
    tags: ["Phishing", "Campaign XYZ"],
    referenceLinks: [
      "https://www.example-threat-intel-site.com/phishing-report-54321",
      "https://www.example-campaign-analysis-site.com/campaign-xyz-analysis",
    ],
  },
  {
    indicator: "CVE-2023-12345",
    indicatorType: "Vulnerability",
    description: "Critical remote code execution vulnerability",
    source: "National Vulnerability Database (NVD)",
    confidenceLevel: "High",
    severity: "Critical",
    dateAdded: "2023-09-10T16:15:00Z",
    tags: ["CVE", "Remote Code Execution"],
    referenceLinks: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-12345",
      "https://www.example-vulnerability-advisory-site.com/vulnerability-patch-advisory",
    ],
  },
  {
    indicator: "APT Group 42",
    indicatorType: "Threat Actor",
    description:
      "Advanced Persistent Threat group known for targeting financial institutions",
    source: "Threat Intelligence Feed C",
    confidenceLevel: "High",
    severity: "High",
    dateAdded: "2023-09-20T11:00:00Z",
    tags: ["APT", "Financial Sector"],
    referenceLinks: [
      "https://www.example-threat-intel-site.com/apt-group-profile",
      "https://www.example-financial-threat-report-site.com/financial-sector-threat-report",
    ],
  },
  {
    indicator: "45.67.89.10",
    indicatorType: "IP Address",
    description: "Malicious IP associated with ransomware campaign",
    source: "Threat Intelligence Feed D",
    confidenceLevel: "Medium",
    severity: "High",
    dateAdded: "2023-09-25T08:20:00Z",
    tags: ["Ransomware", "Campaign ABC"],
    referenceLinks: [
      "https://www.example-threat-intel-site.com/ransomware-report-98765",
      "https://www.example-campaign-analysis-site.com/campaign-abc-analysis",
    ],
  },
  {
    indicator: "example.org",
    indicatorType: "Domain",
    description: "Suspicious domain associated with phishing attempts",
    source: "Threat Intelligence Feed E",
    confidenceLevel: "High",
    severity: "Medium",
    dateAdded: "2023-09-28T15:10:00Z",
    tags: ["Phishing", "Suspicious Domain"],
    referenceLinks: [
      "https://www.example-threat-intel-site.com/phishing-domain-report-54321",
      "https://www.example-analysis-site.com/suspicious-domain-analysis",
    ],
  },
  {
    indicator: "54.32.21.10",
    indicatorType: "IP Address",
    description: "Malicious IP associated with DDoS attacks",
    source: "Threat Intelligence Feed F",
    confidenceLevel: "Medium",
    severity: "High",
    dateAdded: "2023-09-30T12:40:00Z",
    tags: ["DDoS", "Malicious IP"],
    referenceLinks: [
      "https://www.example-threat-feed-f.com/ddos-threat-report-123",
      "https://www.example-analysis-site.com/malicious-ip-ddos-analysis",
    ],
  },
  {
    indicator: "example.net",
    indicatorType: "Domain",
    description: "Suspicious domain with known phishing history",
    source: "Threat Intelligence Feed G",
    confidenceLevel: "High",
    severity: "Medium",
    dateAdded: "2023-10-02T09:15:00Z",
    tags: ["Phishing", "Suspicious Domain"],
    referenceLinks: [
      "https://www.example-threat-feed-g.com/phishing-domain-report-789",
      "https://www.example-analysis-site.com/suspicious-domain-phishing-history",
    ],
  },
  {
    indicator: "CVE-2023-54321",
    indicatorType: "Vulnerability",
    description: "Critical remote code execution vulnerability in widely used software",
    source: "National Vulnerability Database (NVD)",
    confidenceLevel: "High",
    severity: "Critical",
    dateAdded: "2023-10-05T14:55:00Z",
    tags: ["CVE", "Remote Code Execution"],
    referenceLinks: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-54321",
      "https://www.example-vulnerability-advisory-site.com/cve-2023-54321-details",
    ],
  },
  {
    indicator: "APT Group 23",
    indicatorType: "Threat Actor",
    description: "Nation-state-backed APT group targeting critical infrastructure",
    source: "Threat Intelligence Feed H",
    confidenceLevel: "High",
    severity: "High",
    dateAdded: "2023-10-08T10:20:00Z",
    tags: ["APT", "Critical Infrastructure"],
    referenceLinks: [
      "https://www.example-threat-feed-h.com/apt-group-profile",
      "https://www.example-critical-infrastructure-threat-report-site.com/apt-group-23-threat-report",
    ],
  },
];
