export const alertsData = [
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Unauthorized access attempt detected.",
    source: "Firewall",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "High network traffic volume observed.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Disk space on server is critically low.",
    source: "Server Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Malware detected on endpoint.",
    source: "Antivirus",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application server is unresponsive.",
    source: "Application Monitor",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Suspicious login activity detected.",
    source: "Security System",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Network latency exceeding threshold.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Server CPU utilization is high.",
    source: "Server Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Intrusion attempt blocked.",
    source: "Intrusion Detection System",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application error rate above normal.",
    source: "Application Monitor",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Unauthorized file access detected.",
    source: "File Integrity Monitoring",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Unusual network port activity.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Server memory usage is high.",
    source: "Server Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Suspicious email attachment detected.",
    source: "Email Security",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application database connection issue.",
    source: "Application Monitor",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Firewall rule violation detected.",
    source: "Firewall",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "DNS resolution failure on the network.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Server disk I/O is abnormally high.",
    source: "Server Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Brute-force attack detected on SSH.",
    source: "Security System",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application version outdated.",
    source: "Application Monitor",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Failed login attempt from suspicious IP address.",
    source: "Security System",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Unexpected traffic pattern detected on VLAN 10.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Critical system process crashed on server.",
    source: "Server Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Data exfiltration attempt detected.",
    source: "Intrusion Detection System",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application login failures exceeding threshold.",
    source: "Application Monitor",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Unauthorized access to sensitive database.",
    source: "Database Security",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Port scan detected from external source.",
    source: "Firewall",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Server hardware failure reported.",
    source: "Server Hardware Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Malicious URL accessed in web browser.",
    source: "Web Security",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "Application crash reported by users.",
    source: "Application Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Unauthorized software installation detected.",
    source: "Software Management",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Network congestion on backbone links.",
    source: "Network Monitor",
    status: "Open",
  },
  {
    type: "System Alert",
    dateTime: new Date(),
    description: "Server power supply failure reported.",
    source: "Server Hardware Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "Unusual email attachment behavior detected.",
    source: "Email Security",
    status: "Open",
  },
  {
    type: "Application Alert",
    dateTime: new Date(),
    description: "High application error rate in production.",
    source: "Application Monitoring",
    status: "Open",
  },
  {
    type: "Security Alert",
    dateTime: new Date(),
    description: "VPN connection from an unusual location.",
    source: "VPN Gateway",
    status: "Open",
  },
  {
    type: "Network Alert",
    dateTime: new Date(),
    description: "Unexpected broadcast storm in LAN.",
    source: "Network Monitor",
    status: "Open",
  },
];
