const authenticationLogs = [
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "jdoe",
    sourceIp: "192.168.1.100",
    result: "Success",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "jdoe",
    sourceIp: "192.168.1.101",
    result: "Success",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "asmith",
    sourceIp: "192.168.1.102",
    result: "Success",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "jwilliams",
    sourceIp: "192.168.1.103",
    result: "Success",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "mjohnson",
    sourceIp: "192.168.1.104",
    result: "Success",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "rwhite",
    sourceIp: "192.168.1.105",
    result: "Failed",
  },
  {
    eventType: "Authentication",
    dateTime: new Date(),
    user: "ksmith",
    sourceIp: "192.168.1.106",
    result: "Success",
  },
];
const intrusionDetectionLogs = [
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 789012,
    sourceIp: "10.0.0.6",
    destinationIp: "192.168.1.51",
    severity: "Medium",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 345678,
    sourceIp: "10.0.0.7",
    destinationIp: "192.168.1.52",
    severity: "High",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 123789,
    sourceIp: "10.0.0.8",
    destinationIp: "192.168.1.53",
    severity: "High",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 567890,
    sourceIp: "10.0.0.9",
    destinationIp: "192.168.1.54",
    severity: "Low",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 901234,
    sourceIp: "10.0.0.10",
    destinationIp: "192.168.1.55",
    severity: "Medium",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 234567,
    sourceIp: "10.0.0.11",
    destinationIp: "192.168.1.56",
    severity: "High",
  },
  {
    eventType: "IntrusionDetection",
    dateTime: new Date(),
    signatureId: 678901,
    sourceIp: "10.0.0.12",
    destinationIp: "192.168.1.57",
    severity: "Medium",
  },
];
const antiVirusLogs = [
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "trojan.exe",
    user: "jdoe",
    actionTaken: "Quarantined",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "malware.doc",
    user: "asmith",
    actionTaken: "Deleted",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "virus.zip",
    user: "jwilliams",
    actionTaken: "Quarantined",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "ransomware.pdf",
    user: "mjohnson",
    actionTaken: "Deleted",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "adware.png",
    user: "rwhite",
    actionTaken: "Quarantined",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "spyware.txt",
    user: "ksmith",
    actionTaken: "Deleted",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "rootkit.zip",
    user: "cjones",
    actionTaken: "Quarantined",
  },
  {
    eventType: "Antivirus",
    dateTime: new Date(),
    fileName: "malware.exe",
    user: "jsmith",
    actionTaken: "Quarantined",
  },
];
const webProxyLogs = [
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "jdoe",
    url: "http://blocked-site.com/page1",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "asmith",
    url: "http://malicious-site.com",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "jwilliams",
    url: "http://blocked-site.com/page2",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "mjohnson",
    url: "http://blocked-site.com/page3",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "rwhite",
    url: "http://malicious-site.com/page1",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "ksmith",
    url: "http://blocked-site.com/page4",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "cjones",
    url: "http://malicious-site.com/page2",
    rule: "Block",
  },
  {
    eventType: "WebProxy",
    dateTime: new Date(),
    user: "amiller",
    url: "http://malicious-site.com",
    rule: "Block",
  },
];
const fimLogs = [
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/var/www/index.html",
    user: "www-data",
    changeType: "Modified",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/etc/config.conf",
    user: "root",
    changeType: "Deleted",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/home/user/documents/report.docx",
    user: "user123",
    changeType: "Created",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/var/log/syslog",
    user: "sysadmin",
    changeType: "Modified",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/etc/passwd",
    user: "root",
    changeType: "Modified",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/var/www/images/logo.png",
    user: "www-data",
    changeType: "Created",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/home/user/documents/report.docx",
    user: "user123",
    changeType: "Modified",
  },
  {
    eventType: "FIM",
    dateTime: new Date(),
    filePath: "/var/www/index.html",
    user: "www-data",
    changeType: "Modified",
  },
];
const vpnLogs = [
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "jdoe",
    vpnServer: "vpn.example.com",
    connectionDuration: "30 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "asmith",
    vpnServer: "vpn.example.com",
    connectionDuration: "45 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "jwilliams",
    vpnServer: "vpn.example.com",
    connectionDuration: "20 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "mjohnson",
    vpnServer: "vpn.example.com",
    connectionDuration: "15 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "rwhite",
    vpnServer: "vpn.example.com",
    connectionDuration: "1 hour",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "ksmith",
    vpnServer: "vpn.example.com",
    connectionDuration: "25 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "cjones",
    vpnServer: "vpn.example.com",
    connectionDuration: "40 minutes",
  },
  {
    eventType: "VPN",
    dateTime: new Date(),
    user: "rsmith",
    vpnServer: "vpn.example.com",
    connectionDuration: "45 minutes",
  },
];
const activeDirectoryLogs = [
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "jdoe",
    reason: "Account locked out due to multiple failed login attempts.",
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "asmith",
    reason: "Password reset by administrator.",
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "jwilliams",
    reason: "User account disabled due to inactivity.",
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "mjohnson",
    reason: 'User added to security group "Managers".',
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "rwhite",
    reason: 'User removed from security group "Developers".',
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "ksmith",
    reason: "Password changed by user.",
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "cjones",
    reason: "User account locked due to policy violation.",
  },
  {
    eventType: "ActiveDirectory",
    dateTime: new Date(),
    user: "jbrown",
    reason: "Multiple failed login attempts",
  },
];
const emailSecurityLogs = [
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "spammer@malicious.com",
    recipient: "user@example.com",
    actionTaken: "Quarantined",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "phishing@fakebank.com",
    recipient: "user@example.com",
    actionTaken: "Blocked",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "suspicious@attachment.com",
    recipient: "user@example.com",
    actionTaken: "Scanned",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "advertising@product.com",
    recipient: "user@example.com",
    actionTaken: "Delivered",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "virus@malware.com",
    recipient: "user@example.com",
    actionTaken: "Quarantined",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "important@client.com",
    recipient: "user@example.com",
    actionTaken: "Delivered",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "unsubscribe@spam.com",
    recipient: "user@example.com",
    actionTaken: "Blocked",
  },
  {
    eventType: "EmailSecurity",
    dateTime: new Date(),
    sender: "phishing@malicious.com",
    recipient: "user@example.com",
    actionTaken: "Quarantined",
  },
];
const networkTrafficLogs = [
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "192.168.2.0/24",
    protocol: "UDP",
    anomalyDetected: "High data volume",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "192.168.1.0/24",
    protocol: "TCP",
    anomalyDetected: "High data volume",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "10.0.0.0/16",
    protocol: "UDP",
    anomalyDetected: "Unusual port activity",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "172.16.0.0/12",
    protocol: "TCP",
    anomalyDetected: "DDoS attack detected",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "192.168.2.0/24",
    protocol: "TCP",
    anomalyDetected: "Unusual traffic pattern",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "10.1.1.0/24",
    protocol: "UDP",
    anomalyDetected: "High packet loss",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "192.168.3.0/24",
    protocol: "TCP",
    anomalyDetected: "Port scanning detected",
  },
  {
    eventType: "NetworkTraffic",
    dateTime: new Date(),
    sourceIpRange: "10.2.2.0/24",
    protocol: "TCP",
    anomalyDetected: "Unusual traffic spikes",
  },
];

export const logsData = [
  ...authenticationLogs,
  ...intrusionDetectionLogs,
  ...antiVirusLogs,
  ...webProxyLogs,
  ...fimLogs,
  ...vpnLogs,
  ...activeDirectoryLogs,
  ...emailSecurityLogs,
  ...networkTrafficLogs,
];
