export const reportsData = [
  {
    reportType: "Website Traffic",
    period: "September 2023",
    visitors: 12500,
    pageViews: 45000,
    bounceRate: 0.32,
    conversionRate: 0.05,
  },
  {
    reportType: "Sales Performance",
    period: "Q3 2023",
    totalRevenue: 350000,
    totalOrders: 750,
    averageOrderValue: 466.67,
    topSellingProduct: "Product A",
    topSellingCategory: "Electronics",
  },
  {
    reportType: "Security Incident",
    incidentType: "Data Breach",
    incidentDate: "2023-09-15",
    affectedRecords: 10000,
    incidentSeverity: "Critical",
    incidentDescription: "Unauthorized access to customer data.",
  },
  {
    reportType: "Employee Productivity",
    period: "September 2023",
    totalHoursWorked: 2500,
    averageHoursPerEmployee: 160,
    mostProductiveEmployee: "John Doe",
    leastProductiveEmployee: "Jane Smith",
  },
  {
    reportType: "Customer Satisfaction",
    surveyDate: "2023-09-30",
    overallSatisfaction: 4.5,
    customerFeedback: "Customers appreciate the fast response time of our support team.",
  },
  {
    reportType: "Inventory Analysis",
    period: "Q3 2023",
    totalInventoryValue: 500000,
    averageInventoryTurnover: 4.2,
    outOfStockProducts: ["Product X", "Product Y"],
  },
  {
    reportType: "Network Performance",
    period: "September 2023",
    averageLatency: 12.5,
    networkDowntime: "2 hours",
    mostFrequentIssue: "Packet Loss",
  },
  {
    reportType: "Website Traffic",
    period: "August 2023",
    visitors: 12000,
    pageViews: 43000,
    bounceRate: 0.29,
    conversionRate: 0.06,
  },
  {
    reportType: "Sales Performance",
    period: "Q2 2023",
    totalRevenue: 320000,
    totalOrders: 700,
    averageOrderValue: 457.14,
    topSellingProduct: "Product B",
    topSellingCategory: "Clothing",
  },
  {
    reportType: "Security Incident",
    incidentType: "Phishing Attack",
    incidentDate: "2023-08-20",
    affectedRecords: 7500,
    incidentSeverity: "High",
    incidentDescription: "Phishing emails targeting employees.",
  },
  {
    reportType: "Employee Productivity",
    period: "August 2023",
    totalHoursWorked: 2400,
    averageHoursPerEmployee: 150,
    mostProductiveEmployee: "Michael Johnson",
    leastProductiveEmployee: "Sarah Adams",
  },
  {
    reportType: "Customer Satisfaction",
    surveyDate: "2023-08-31",
    overallSatisfaction: 4.7,
    customerFeedback: "Customers are pleased with our new product offerings.",
  },
  {
    reportType: "Inventory Analysis",
    period: "Q2 2023",
    totalInventoryValue: 480000,
    averageInventoryTurnover: 4.5,
    outOfStockProducts: ["Product C", "Product D"],
  },
  {
    reportType: "Network Performance",
    period: "August 2023",
    averageLatency: 13.2,
    networkDowntime: "1.5 hours",
    mostFrequentIssue: "Slow response times",
  },
  {
    reportType: "Website Traffic",
    period: "July 2023",
    visitors: 11500,
    pageViews: 42000,
    bounceRate: 0.28,
    conversionRate: 0.07,
  },
  {
    reportType: "Sales Performance",
    period: "Q1 2023",
    totalRevenue: 300000,
    totalOrders: 650,
    averageOrderValue: 461.54,
    topSellingProduct: "Product C",
    topSellingCategory: "Electronics",
  },
  {
    reportType: "Security Incident",
    incidentType: "Malware Infection",
    incidentDate: "2023-07-10",
    affectedRecords: 6000,
    incidentSeverity: "Medium",
    incidentDescription: "Malware detected on several endpoints.",
  },
  {
    reportType: "Employee Productivity",
    period: "July 2023",
    totalHoursWorked: 2300,
    averageHoursPerEmployee: 145,
    mostProductiveEmployee: "Emily Turner",
    leastProductiveEmployee: "David Wilson",
  },
  {
    reportType: "Customer Satisfaction",
    surveyDate: "2023-07-31",
    overallSatisfaction: 4.6,
    customerFeedback: "Customers are requesting better mobile app features.",
  },
  {
    reportType: "Inventory Analysis",
    period: "Q1 2023",
    totalInventoryValue: 470000,
    averageInventoryTurnover: 4.8,
    outOfStockProducts: ["Product E", "Product F"],
  },
];
